- name: configuring the payment component
  hosts: payment
  become: yes
  tasks:
  - name: install the application
    ansible.builtin.dnf:
      name: "{{ item }}"
      state: installed
    loop:
    - python3
    - gcc
    - python3-devel



  - name: add the user  
    ansible.builtin.user:
      name: roboshop
      home: /app
      shell: /sbin/nologin
      system: true

  - name: create the app directory
    ansible.builtin.file:
      path: /app
      state: directory


  - name: download the code
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/payment-v3.zip
      dest: /tmp/payment.zip

  - name: extract the code
    ansible.builtin.unarchive:
      src: /tmp/payment.zip
      dest: /app
      remote_src: yes

  - name: Install specified python requirements
    ansible.builtin.pip:
      requirements: requirements.txt
      executable: pip3.9
    args:
      chdir: /app

  - name: copy the service file
    ansible.builtin.copy:
      src: payment.service
      dest: /etc/systemd/system/payment.service

  - name: daeomon_reload
    ansible.builtin.systemd_service:
      daemon_reload: true

  - name: Start and enable the payment service
    ansible.builtin.service:
      name: payment
      state: started
      enabled: yes